from __future__ import annotations

from typing import Any

from .utils import sentence_split, utc_now_iso


def demo_source_results(issue_date: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    retrieved = utc_now_iso()
    scholarly = [
        {
            "record_type": "scholarly_source",
            "source_id": "pubmed",
            "source_record_id": "99900001",
            "query_group": "genomics",
            "query": "hantavirus genome",
            "identifiers": {"pmid": "99900001", "doi": "10.0000/demo.hanta.2026"},
            "title": "Genomic surveillance of orthohantaviruses across rodent reservoirs",
            "abstract": "This demonstration record evaluates genomic surveillance of orthohantaviruses in rodent reservoirs in China. The study reports sequencing and phylogenetic analysis without claiming a new outbreak.",
            "abstract_sentences": sentence_split("This demonstration record evaluates genomic surveillance of orthohantaviruses in rodent reservoirs in China. The study reports sequencing and phylogenetic analysis without claiming a new outbreak.", "A"),
            "authors": ["Demo Zhang", "Example Li"],
            "journal": "Demonstration Journal of Viral Surveillance",
            "published_date": issue_date,
            "published_date_precision": "day",
            "language": "eng",
            "url": "https://pubmed.ncbi.nlm.nih.gov/99900001/",
            "retrieved_at": retrieved,
        },
        {
            "record_type": "scholarly_source",
            "source_id": "europe_pmc",
            "source_record_id": "MED/99900001",
            "query_group": "genomics",
            "query": "hantavirus genome",
            "identifiers": {"pmid": "99900001", "doi": "10.0000/demo.hanta.2026", "europe_pmc_id": "MED/99900001"},
            "title": "Genomic surveillance of orthohantaviruses across rodent reservoirs",
            "abstract": "This demonstration record evaluates genomic surveillance of orthohantaviruses in rodent reservoirs in China. The study reports sequencing and phylogenetic analysis without claiming a new outbreak.",
            "abstract_sentences": sentence_split("This demonstration record evaluates genomic surveillance of orthohantaviruses in rodent reservoirs in China. The study reports sequencing and phylogenetic analysis without claiming a new outbreak.", "A"),
            "authors": ["Demo Zhang", "Example Li"],
            "journal": "Demonstration Journal of Viral Surveillance",
            "published_date": issue_date,
            "published_date_precision": "day",
            "language": "en",
            "url": "https://europepmc.org/article/MED/99900001",
            "retrieved_at": retrieved,
        },
        {
            "record_type": "scholarly_source",
            "source_id": "crossref",
            "source_record_id": "10.0000/demo.hfrs.2026",
            "query_group": "clinical",
            "query": "hemorrhagic fever with renal syndrome",
            "identifiers": {"doi": "10.0000/demo.hfrs.2026"},
            "title": "Serological surveillance of hemorrhagic fever with renal syndrome",
            "abstract": None,
            "abstract_sentences": [],
            "authors": ["Example Wang"],
            "journal": "Demo Epidemiology Reports",
            "published_date": issue_date,
            "published_date_precision": "day",
            "language": "en",
            "url": "https://doi.org/10.0000/demo.hfrs.2026",
            "retrieved_at": retrieved,
        },
    ]
    news = [
        {
            "source_id": "demo_health_authority",
            "source_name": "Demonstration Health Authority",
            "source_category": "official",
            "source_tier": "A",
            "domain": "example.org",
            "title": "Laboratory confirms 2 hantavirus pulmonary syndrome cases in Chile",
            "url": "https://example.org/notices/hantavirus-cases",
            "canonical_url": "https://example.org/notices/hantavirus-cases",
            "published_at": issue_date,
            "excerpt": "The authority reported 2 laboratory-confirmed cases of hantavirus pulmonary syndrome in Chile and announced epidemiological investigation.",
            "content_sentences": sentence_split("The authority reported 2 laboratory-confirmed cases of hantavirus pulmonary syndrome in Chile and announced epidemiological investigation.", "N"),
            "language": "en",
            "query_group": "outbreak",
            "query": "hantavirus cases",
            "retrieved_at": retrieved,
            "original_source": "Demonstration Health Authority",
        },
        {
            "source_id": "google_news_en",
            "source_name": "Google News RSS English",
            "source_category": "discoverer",
            "source_tier": "D",
            "domain": "news.example.net",
            "title": "Two hantavirus pulmonary syndrome cases confirmed in Chile",
            "url": "https://news.example.net/story?utm_source=rss&id=1",
            "canonical_url": "https://news.example.net/story?id=1",
            "published_at": issue_date,
            "excerpt": "Media coverage repeats the health authority report of 2 laboratory-confirmed cases in Chile.",
            "content_sentences": sentence_split("Media coverage repeats the health authority report of 2 laboratory-confirmed cases in Chile.", "N"),
            "language": "en",
            "query_group": "outbreak",
            "query": "hantavirus cases",
            "retrieved_at": retrieved,
            "original_source": "Example News",
        },
        {
            "source_id": "demo_lab",
            "source_name": "Demonstration Public Health Laboratory",
            "source_category": "official",
            "source_tier": "A",
            "domain": "lab.example.org",
            "title": "中国开展汉坦病毒啮齿动物宿主监测",
            "url": "https://lab.example.org/zh/rodent-surveillance",
            "canonical_url": "https://lab.example.org/zh/rodent-surveillance",
            "published_at": issue_date,
            "excerpt": "公共卫生实验室报告开展汉坦病毒啮齿动物宿主监测，未报告人类病例。",
            "content_sentences": sentence_split("公共卫生实验室报告开展汉坦病毒啮齿动物宿主监测，未报告人类病例。", "N"),
            "language": "zh",
            "query_group": "ecology",
            "query": "汉坦病毒 宿主监测",
            "retrieved_at": retrieved,
            "original_source": "示例公共卫生实验室",
        },
    ]
    health = [
        {"source_id": "pubmed", "status": "success_with_results", "record_count": 1, "query_count": 1, "errors": [], "audits": []},
        {"source_id": "europe_pmc", "status": "success_with_results", "record_count": 1, "query_count": 1, "errors": [], "audits": []},
        {"source_id": "crossref", "status": "success_with_results", "record_count": 1, "query_count": 1, "errors": [], "audits": []},
        {"source_id": "semantic_scholar", "status": "success_no_results", "record_count": 0, "query_count": 1, "errors": [], "audits": []},
        {"source_id": "demo_official_news", "status": "success_with_results", "record_count": 3, "query_count": 2, "errors": [], "audits": []},
    ]
    return scholarly, news, health
